# Use official lightweight Python image
FROM python:3.11-slim

# Install system dependencies (Tesseract + Poppler)
RUN apt-get update && apt-get install -y tesseract-ocr poppler-utils

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Render runtime port
EXPOSE 5000

# Run Flask app.
CMD ["python", "app.py"]
